ignore:
  - vulnerability: CVE-2021-33560
    type: deb
    fix-state: wont-fix
    package:
      name: libgcrypt20
  - vulnerability: CVE-2011-3389
    type: deb
    package:
      name: libgnutls30
  - vulnerability: CVE-2020-16156
    type: deb
    fix-state: wont-fix
