ignore:
  - vulnerability: CVE-2021-31879
    type: deb
    package:
      name: wget
  - vulnerability: CVE-2022-37434
    type: deb
    package:
      name: zlib1g
  - vulnerability: CVE-2022-42800
    type: deb
    package:
      name: zlib1g
  - vulnerability: CVE-2022-3715
    type: deb
    package:
      name: bash
  - vulnerability: CVE-2022-3821
    type: deb
    package:
      name: libsystemd0
  - vulnerability: CVE-2022-3821
    type: deb
    package:
      name: libudev1
