ignore:
  - vulnerability: CVE-2021-31879
    type: deb
    package:
      name: wget
  - vulnerability: CVE-2022-3821
    type: deb
    package:
      name: libsystemd0
  - vulnerability: CVE-2022-3821
    type: deb
    package:
      name: libudev1
  - vulnerability: CVE-2022-42898
    type: deb
