ignore:
  - vulnerability: CVE-2020-16156
    type: deb
    package:
      name: perl-base
  - vulnerability: CVE-2021-31879
    type: deb
    package:
      name: wget
  - vulnerability: CVE-2022-37434
    type: deb
    package:
      name: zlib1g
