name: BUILD-SCAN-PUSH

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:

  get-matrix-values:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-var.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - id: set-var
        run: |
          {
            echo "image<<JSON"
            cat ./image-matrix.json
            echo "JSON"
          } >> "$GITHUB_OUTPUT"
  
  build-images:
    runs-on: ubuntu-latest
    needs:  get-matrix-values
    strategy:
      matrix:
        target: ["development", "production"]
        image: ${{fromJSON(needs.get-matrix-values.outputs.image)}}
    steps:
      - uses: actions/checkout@v3
      - id: setEnv
        name: Set Job env vars 
        run: |
          cat JOB.env >> $GITHUB_ENV

      - id: setImageDetails
        name: Set image name and latest tag
        run: |
          if [ ${{matrix.target}} = "production" ]
          then 
            DOCKER_REPO_NAME="defradigital/$IMAGE_NAME"
          else
            DOCKER_REPO_NAME="defradigital/$IMAGE_NAME-${{matrix.target}}"
          fi
          
          echo "dockerRepoName=$DOCKER_REPO_NAME" >> $GITHUB_OUTPUT
          echo "fullImageName=$DOCKER_REPO_NAME:$DEFRA_VERSION-$GITHUB_RUN_NUMBER-java-${{matrix.image.runtimeVersion}}" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --no-cache \
          --target=${{matrix.target}} \
          --build-arg DEFRA_VERSION=$DEFRA_VERSION \
          --build-arg BASE_VERSION=${{matrix.image.runtimeVersion}}  \
          --tag ${{steps.setImageDetails.outputs.fullImageName}}
          docker images

      - name: run anchore grype scan
        id: grype-scan
        if: ${{ matrix.target == 'production' }}
        uses: anchore/scan-action@v6
        with:
          image: ${{steps.setImageDetails.outputs.fullImageName}}
          fail-build: false
          severity-cutoff: "medium"
        continue-on-error: true

      - name: Run Aqua Trivy scan
        id: trivy-scan
        if: ${{ matrix.target == 'production' }}
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{steps.setImageDetails.outputs.fullImageName}}
          format: sarif
          output: trivy-reports-java-${{ matrix.image.runtimeVersion }}
          exit-code: 1
          vuln-type: os,library
          severity: CRITICAL,HIGH,MEDIUM
          ignore-unfixed: true
        continue-on-error: true

      - name: Upload Grype SARIF report
        if: ${{ steps.grype-scan.outcome == 'failure' && matrix.target == 'production' }}
        uses: actions/upload-artifact@v4
        with:
          name: grype-reports-java-${{ matrix.image.runtimeVersion }}
          path: ${{ steps.grype-scan.outputs.sarif }}

      - name: Upload Trivy SARIF report
        if: ${{ steps.trivy-scan.outcome == 'failure' && matrix.target == 'production' }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports-java-${{ matrix.image.runtimeVersion }}
          path: trivy-reports-java-${{ matrix.image.runtimeVersion }}

      - name: Fail build if scans failed
        if: ${{ (steps.grype-scan.outcome == 'failure' || steps.trivy-scan.outcome == 'failure') && matrix.target == 'production' }}
        run: |
          echo "One or more scans failed. Failing the build."
          exit 1

      - name: Tag image
        run: |
          echo "Tags are ${{ join(matrix.image.tags, ' ') }}"
          for TAG in ${{ join(matrix.image.tags, ' ') }}
          do
            echo "github.ref  " ${{github.ref}}
            echo "creating tag ${{steps.setImageDetails.outputs.dockerRepoName}}:$TAG"
            docker image tag ${{steps.setImageDetails.outputs.fullImageName}} ${{steps.setImageDetails.outputs.dockerRepoName}}:$TAG
          done

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main' || matrix.target == 'development'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - id: pushImage
        name: push docker image
        if: github.ref == 'refs/heads/main' || matrix.target == 'development'
        run: |
          docker image push ${{steps.setImageDetails.outputs.fullImageName}}
          for TAG in ${{ join(matrix.image.tags, ' ') }}
          do
            docker image push ${{steps.setImageDetails.outputs.dockerRepoName}}:$TAG
          done

      - name: Inspect action SARIF report
        if: always() && steps.scan.outputs.sarif
        run: cat ${{ steps.scan.outputs.sarif }}