name: BUILD-SCAN-PUSH

on: [push, pull_request, workflow_dispatch]

jobs:

  get-matrix-values:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-var.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - id: set-var
        run: |
          echo 'image<<EOF' >> $GITHUB_OUTPUT
          cat ./image-matrix.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  
  build-images:
    runs-on: ubuntu-latest
    needs:  get-matrix-values
    strategy:
      matrix:
        target: ["production"]
        image: ${{fromJSON(needs.get-matrix-values.outputs.image)}}
    steps:
      - uses: actions/checkout@v3
      - id: setEnv
        name: Set Job env vars 
        run: |
          cat JOB.env >> $GITHUB_ENV

      - id: setImageDetails
        name: Set image name and latest tag
        run: |
          if [ ${{matrix.target}} = "production" ]
          then 
            DOCKER_REPO_NAME="defradigital/$IMAGE_NAME"
          else
            DOCKER_REPO_NAME="defradigital/$IMAGE_NAME-${{matrix.target}}"
          fi
          
          echo "dockerRepoName=$DOCKER_REPO_NAME" >> $GITHUB_OUTPUT
          echo "fullImageName=$DOCKER_REPO_NAME:$DEFRA_VERSION-java${{matrix.image.runTimeVersion}}" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --no-cache \
          --target=${{matrix.target}} \
          --build-arg DEFRA_VERSION=$DEFRA_VERSION \
          --build-arg BASE_VERSION=${{matrix.image.runtimeVersion}}  \
          --tag ${{steps.setImageDetails.outputs.fullImageName}}
          docker images

      - name: run anchore grype scan
        id: scan
        if: ${{ matrix.target == 'production' }}
        uses: anchore/scan-action@v3
        with:
          image: ${{steps.setImageDetails.outputs.fullImageName}}
          fail-build: false
          severity-cutoff: "medium"
          output-format: "sarif"

      - name: Tag image
        run: |
          echo "Tags are ${{ join(matrix.image.tags, ' ') }}"
          for TAG in ${{ join(matrix.image.tags, ' ') }}
          do
            echo "github.ref  " ${{github.ref}}
            echo "creating tag ${{steps.setImageDetails.outputs.dockerRepoName}}:$TAG"
            docker image tag ${{steps.setImageDetails.outputs.fullImageName}} ${{steps.setImageDetails.outputs.dockerRepoName}}:$TAG
          done

      - name: Login to DockerHub
        uses: docker/login-action@v2
       ## if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - id: pushImage
        name: push docker image
        ##if: github.ref == 'refs/heads/main'
        run: |
          docker image push ${{steps.setImageDetails.outputs.fullImageName}}
          for TAG in ${{ join(matrix.image.tags, ' ') }}
          do
            docker image push ${{steps.setImageDetails.outputs.dockerRepoName}}:$TAG
          done

      - name: Upload Anchore Grype SARIF report
        if: always() && steps.scan.outputs.sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Inspect action SARIF report
        if: always() && steps.scan.outputs.sarif
        run: cat ${{ steps.scan.outputs.sarif }}